# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
# Kamal Malkani

version: '2'

services:

  orderer.tietonetworks.com:
    container_name: orderer.tietonetworks.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS      
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/tietonetworks.com/orderers/orderer.tietonetworks.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/tietonetworks.com/orderers/orderer.tietonetworks.com/tls:/var/hyperledger/orderer/tls
    - ./crypto-config/ordererOrganizations/tietonetworks.com/orderers/orderer.tietonetworks.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer1.upm.tietonetworks.com:
    container_name: peer1.upm.tietonetworks.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.upm.tietonetworks.com
      - CORE_PEER_ADDRESS=peer1.upm.tietonetworks.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.upm.tietonetworks.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.upm.tietonetworks.com:7051
      - CORE_PEER_LOCALMSPID=UpmMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/upm.tietonetworks.com/peers/peer1.upm.tietonetworks.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/upm.tietonetworks.com/peers/peer1.upm.tietonetworks.com/tls:/etc/hyperledger/fabric/tls
        - ./crypto-config/peerOrganizations/upm.tietonetworks.com/peers/peer1.upm.tietonetworks.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer1.dhl.tietonetworks.com:
    container_name: peer1.dhl.tietonetworks.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dhl.tietonetworks.com
      - CORE_PEER_ADDRESS=peer1.dhl.tietonetworks.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dhl.tietonetworks.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dhl.tietonetworks.com:7051
      - CORE_PEER_LOCALMSPID=DhlMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/dhl.tietonetworks.com/peers/peer1.dhl.tietonetworks.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/dhl.tietonetworks.com/peers/peer1.dhl.tietonetworks.com/tls:/etc/hyperledger/fabric/tls
        - ./crypto-config/peerOrganizations/upm.tietonetworks.com/peers/peer1.dhl.tietonetworks.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
  
  peer1.finport.tietonetworks.com:
    container_name: peer1.finport.tietonetworks.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.finport.tietonetworks.com
      - CORE_PEER_ADDRESS=peer1.finport.tietonetworks.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.finport.tietonetworks.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.finport.tietonetworks.com:7051
      - CORE_PEER_LOCALMSPID=FinportMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/finport.tietonetworks.com/peers/peer1.finport.tietonetworks.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/finport.tietonetworks.com/peers/peer1.finport.tietonetworks.com/tls:/etc/hyperledger/fabric/tls
        - ./crypto-config/peerOrganizations/upm.tietonetworks.com/peers/peer1.finport.tietonetworks.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053